spring.profiles.active: dev

---
spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
  datasource:
    hikari:
      jdbc-url:
      username:
      password:

---

spring:
  profiles: prod


rabbitmq:
  bus.exchange: hi

---


